// English message catalog. Source of truth — `Messages = typeof en`, so any
// other locale (de.ts) is type-checked against this. Adding a key here forces
// every other locale to add it too. Removing a key forces a sweep of callers.
//
// Keys are flat (TS `keyof` constraint) and grouped by area via prefixes:
//   nav_*       bottom nav tab labels
//   header_*    page-header titles, share button, locale switcher
//   play_*      Play tab
//   create_*    Create tab
//   print_*     Print tab
//   howto_*     How-to tab
//   wt_*        Walkthrough tab (text + plurals)
//   wt_rule_*   Walkthrough propagation-rule labels & descriptions
//   cls_*       Classification chip labels
//   toast_*     Transient toasts
//   share_*     Web Share / clipboard
//   aria_*      Aria-labels for buttons that have only an icon
//   err_*       Errors, including translated wasm errors
//
// Inline-bold marker: `{*…*}` (see `md()` in index.svelte.ts).
// Placeholders: `{n}`, `{name}` etc., substituted at call site with `format()`.

export const en = {
  // Bottom nav
  nav_play: 'Play',
  nav_steps: 'Walkthrough',
  nav_create: 'Create',
  nav_print: 'Print',
  nav_howto: 'How to play',
  nav_aria: 'Main sections',

  // Page header
  header_share: 'Share',
  header_share_aria: 'Share',
  header_locale_aria: 'Language',

  // Play tab
  play_title: 'Play',
  play_new_puzzle: 'New puzzle',
  play_undo: 'Undo',
  play_redo: 'Redo',
  play_check: 'Check',
  play_check_aria: 'Check answers',
  play_undo_aria: 'Undo',
  play_redo_aria: 'Redo',
  play_notes_mode: 'Notes mode',
  play_space_to_switch: 'Space to switch',
  play_hint_chip: 'Tap for a note · hold for the answer',
  play_hint_dismiss_aria: 'Dismiss hint',
  play_status_switching: 'Switching…',
  play_status_generating: 'Generating…',

  // InputBar
  inputbar_aria: 'Input buttons',
  inputbar_black_aria: 'Black cell (hold) / note (tap)',
  inputbar_digit_aria: 'Digit {n} (hold to place, tap for note)',
  inputbar_o_aria: 'Must be a digit (note)',
  inputbar_erase_aria: 'Erase cell',

  // Create tab
  create_title: 'Create',
  create_set_target_aria: 'Set target to {n}',
  create_values_aria: 'Target value buttons',
  create_use: 'Use this puzzle',
  create_use_aria: 'Use this puzzle',
  create_use_title_valid: 'Send this puzzle to the Play tab',
  create_use_title_invalid: 'Only puzzles with a unique solution can be used',
  create_share_invalid: "Can't share an invalid puzzle",

  // Print tab
  print_title: 'Print',
  print_status: 'Generate a printable booklet',
  print_size: 'Size',
  print_pages: 'Pages',
  print_six_per_page: 'Six puzzles per page',
  print_fewer_aria: 'Fewer pages',
  print_more_aria: 'More pages',
  print_busy: 'Generating…',
  print_btn_one: 'Generate {n} page',
  print_btn_other: 'Generate {n} pages',
  print_footnote: 'Larger sizes and longer booklets take a moment to generate.',

  // Print output
  print_promo: 'Doplo puzzles generated by {url}',

  // How-to tab
  howto_title: 'How to play',
  howto_intro:
    'Each row and column has a {*target*} at its head. Place the digits and two black squares so the puzzle makes sense:',
  howto_rule1_title: 'Two blacks',
  howto_rule1_body: 'Each row and each column contains exactly {*two black squares*}.',
  howto_rule2_title: 'A permutation in between',
  howto_rule2_body:
    'The other cells in each row and column hold the digits {*1 to N − 2*} — each appearing once.',
  howto_rule3_title: 'Sum to the target',
  howto_rule3_body:
    'The numbers {*between*} the two blacks must add up to the target shown. A target of {*0*} means the two blacks are adjacent.',
  howto_example_heading: 'Step-by-step example',
  howto_example_intro:
    'Here is a fresh 5 × 5 puzzle. The digits used are 1, 2, and 3. Where do you start?',
  howto_step1_heading: 'Step 1 — Row target 6 is the maximum possible sum',
  howto_step1_body:
    'Digits 1 + 2 + 3 = {*6*}. Target 6 means every digit lies between the two blacks, so blacks go at the very ends: column 1 and column 5.',
  howto_step2_heading: 'Step 2 — Column 5 target 0 means the blacks are neighbours',
  howto_step2_body:
    'Target 0 means nothing between the blacks — they must be adjacent. Column 5 already has a black in row 1, so the second black sits immediately below in row 2.',
  howto_step3_heading: 'Step 3 — Row 2 target 2 pins the second black',
  howto_step3_body:
    'Row 2 already has a black at column 5. Target 2 means exactly digit {*2*} sits between the blacks. Place 2 at column 4, and the second black at column 3.',
  howto_outro:
    'Each deduction unlocks the next. Keep going until the puzzle is complete — there is always exactly one solution.',
  howto_controls_heading: 'Controls',
  howto_controls_action: 'Action',
  howto_controls_touch: 'Touch / mouse',
  howto_controls_kb: 'Keyboard',
  howto_ctrl_place_note: 'Place a note',
  howto_ctrl_place_note_touch: 'Tap button',
  howto_ctrl_place_note_kb: 'Space, then digit',
  howto_ctrl_place_value: 'Place an answer',
  howto_ctrl_place_value_touch: 'Hold button',
  howto_ctrl_place_value_kb: 'Digit (default)',
  howto_ctrl_toggle_mode: 'Toggle note/value mode',
  howto_ctrl_toggle_mode_touch: '—',
  howto_ctrl_toggle_mode_kb: 'Space',
  howto_ctrl_mark_black: 'Mark cell black',
  howto_ctrl_mark_black_touch: 'Hold ■',
  howto_ctrl_mark_black_kb: '0, B, or X',
  howto_ctrl_mark_digits: 'Mark digits-only',
  howto_ctrl_mark_digits_touch: 'Tap ○',
  howto_ctrl_mark_digits_kb: '9 or O',
  howto_ctrl_erase: 'Erase cell',
  howto_ctrl_erase_touch: 'Tap eraser',
  howto_ctrl_erase_kb: 'Backspace / Delete',
  howto_ctrl_move: 'Move selection',
  howto_ctrl_move_touch: 'Tap cell',
  howto_ctrl_move_kb: 'Arrow keys / WASD',
  howto_source: 'Source code:',

  // Walkthrough tab
  wt_title: 'Walkthrough',
  wt_status_no_puzzle: 'No puzzle loaded.',
  wt_placeholder:
    'Pick a puzzle on the {*Play*} or {*Create*} tab. The step-by-step solution will appear here.',
  wt_error: 'Could not generate a walkthrough: {err}',
  wt_intro1:
    'Watch the solver chip away at the current puzzle. Each grid below is one {*wave*} — every change in a wave can be made from what was known before it.',
  wt_intro2:
    'Cells start with every digit (small numbers) plus an {*x*} for "could be black". As options get ruled out, the notes shrink. When only one option is left, the cell is filled in. Cells that changed in a wave are highlighted in yellow.',
  wt_start: 'Start',
  wt_start_sub: 'Every cell could still hold any digit or be black.',
  wt_wave: 'Wave {n}',
  wt_wave_one: '· {n} note removed',
  wt_wave_other: '· {n} notes removed',
  wt_search: 'Search',
  wt_guess_one: '· {n} guess',
  wt_guess_other: '· {n} guesses',
  wt_search_sub:
    "Pure deduction can't crack this one — from here the solver tries hypotheses and backtracks. The remaining work is too dense to draw out grid by grid, so we skip ahead to the answer.",
  wt_solved: 'Solved',
  wt_solved_sub: 'The final puzzle.',
  wt_status_waves_one: '{n} wave',
  wt_status_waves_other: '{n} waves',
  wt_status_removed_one: '{n} note removed',
  wt_status_removed_other: '{n} notes removed',
  wt_status_join: ' · ',

  // Walkthrough rule labels
  wt_rule_target_tuples: 'Target sums',
  wt_rule_arc: 'Possibility check',
  wt_rule_singleton: 'Forced cells',
  wt_rule_hidden: 'Only place',
  wt_rule_black: 'Two-blacks rule',
  wt_rule_backtrack: 'Hypothesis',

  // Walkthrough rule notes — solo: shown when only this rule fires in a wave.
  wt_rule_target_tuples_note:
    'Some digit or black placements simply cannot be part of any arrangement that adds up to the row or column target — those are removed.',
  wt_rule_arc_note:
    'No remaining arrangement of this row or column still supports these options, so they are eliminated.',
  wt_rule_singleton_note:
    'A nearby cell is now fully determined, and its value cannot repeat in the rest of its row or column.',
  wt_rule_hidden_note:
    'Only one cell in this row or column can still hold this digit or black, so the others lose it as a candidate.',
  wt_rule_black_note:
    'Each row and each column has exactly two blacks. These options would create a third one — so they go.',
  wt_rule_backtrack_note:
    'The solver tried a guess to break a deadlock. Rare for hand-solvable puzzles.',

  // Walkthrough rule notes — dominant: shown when this rule leads a mixed wave.
  wt_rule_target_tuples_dominant:
    'Most eliminations in this wave come from target sums — some digit or black placements simply cannot be part of any arrangement that adds up to the row or column target.',
  wt_rule_arc_dominant:
    'Most eliminations in this wave come from possibility checks — no remaining arrangement of the row or column still supports these options.',
  wt_rule_singleton_dominant:
    'Most eliminations in this wave come from forced cells — a nearby cell is now fully determined, and its value cannot repeat in the rest of its row or column.',
  wt_rule_hidden_dominant:
    'Most eliminations in this wave come from only-place reasoning — only one cell in a row or column can still hold a given digit or black, so the others lose it as a candidate.',
  wt_rule_black_dominant:
    'Most eliminations in this wave come from the two-blacks rule — each row and each column has exactly two blacks, so options that would create a third one are removed.',
  wt_rule_backtrack_dominant:
    'Most eliminations in this wave come from hypotheses — the solver tried guesses to break a deadlock. Rare for hand-solvable puzzles.',

  // Classification chip
  cls_no_solution: 'No solution',
  cls_multiple: 'Multiple solutions',
  cls_normal: 'Normal',
  cls_hard: 'Hard',
  cls_very_hard: 'Very hard',
  cls_extremely_hard: 'Extremely hard',

  // Toasts
  toast_solved: 'Puzzle solved! 🎉',
  toast_check_empty: 'Enter some cells, then check them.',
  toast_check_all_correct: 'All entered cells are correct.',
  toast_one_wrong: 'One wrong cell.',
  toast_n_wrong: '{n} wrong cells.',
  toast_link_copied: 'Link copied to clipboard',
  toast_share_failed: 'Could not share this puzzle',

  // Web Share API
  share_title: 'Doplo puzzle',
  share_text: 'Try this Doplo puzzle:',

  // Wasm errors (mapped from raw Rust strings in web/src/wasm/api.ts)
  err_row_targets_length: 'Row targets length does not match the puzzle size.',
  err_col_targets_length: 'Column targets length does not match the puzzle size.',
  err_targets_length_mismatch: 'Row and column targets must have the same length.',
  err_size_range: 'Size must be between 5 and 8.',
  err_unsolvable: 'Puzzle is unsolvable.',
  err_multiple_solutions: 'Puzzle has multiple solutions.',
  err_incomplete_state: 'Solver returned an incomplete state.',
  err_target_out_of_range: 'Target {t} is out of range (max is {max} for size {size}).',

  // Locale switcher — autonyms (language's own name); same in every catalog.
  loc_en: 'English',
  loc_de: 'Deutsch',
  loc_pt: 'Português',
  loc_fr: 'Français',
};

export type MessageKey = keyof typeof en;
export type Messages = Record<MessageKey, string>;
