<script lang="ts">
  import { onMount } from 'svelte';
  import BottomNav from './BottomNav.svelte';
  import PlayTab from './tabs/PlayTab.svelte';
  import CreateTab from './tabs/CreateTab.svelte';
  import PrintTab from './tabs/PrintTab.svelte';
  import HowToTab from './tabs/HowToTab.svelte';
  import WalkthroughTab from './tabs/WalkthroughTab.svelte';
  import PuzzleGrid from './PuzzleGrid.svelte';
  import { initWasm, generatePuzzle } from '../wasm/api';
  import { reportFatal } from '../error-overlay';
  import { loadRandomPuzzle, setPuzzle } from '../state/puzzle.svelte';
  import {
    parsePuzzleFromUrl,
    clearUrlParams,
    tabFromUrl,
    tabState,
    setTab,
  } from '../state/url.svelte';
  import { trackEvent } from '../analytics';
  import type { PuzzleData } from '../state/types';

  const PUZZLES_PER_BATCH = 6;
  const PROMO = `Doplo puzzles generated by ${window.location.origin}${window.location.pathname}`;

  let ready = $state(false);
  let printBusy = $state(false);

  type PrintGroup = { puzzles: PuzzleData[] };
  const printGroups = $state<PrintGroup[]>([]);

  onMount(async () => {
    const fromUrl = parsePuzzleFromUrl();
    try {
      await initWasm();
      if (fromUrl) {
        setPuzzle(fromUrl);
      } else {
        loadRandomPuzzle(6);
      }
      const t = tabFromUrl();
      if (t !== 'play') setTab(t);

      // Per DESIGN_NOTES.md: clear the URL param after loading — keep URL clean.
      clearUrlParams();

      // Pre-generate one page so Ctrl+P works immediately.
      await fillPrintOutput(6, 1);
      ready = true;
    } catch (err) {
      console.error('Initialization failed:', err);
      reportFatal(err);
    }
  });

  async function fillPrintOutput(size: number, pages: number): Promise<void> {
    const total = pages * PUZZLES_PER_BATCH;
    printGroups.length = 0;
    let generated = 0;
    while (generated < total) {
      const pageSize = Math.min(PUZZLES_PER_BATCH, total - generated);
      const puzzles = Array.from({ length: pageSize }, () => generatePuzzle(size));
      printGroups.push({ puzzles });
      generated += pageSize;
      if (generated < total) await new Promise((resolve) => setTimeout(resolve, 0));
    }
  }

  async function generateAndPrint(size: number, pages: number): Promise<void> {
    printBusy = true;
    trackEvent(`rublock/print/print/${size}`);
    try {
      await fillPrintOutput(size, pages);
      window.print();
    } finally {
      printBusy = false;
    }
  }
</script>

<div class="app-shell">
  <div class="screen-content">
    {#if tabState.active === 'play'}
      <PlayTab />
    {:else if tabState.active === 'create'}
      <CreateTab />
    {:else if tabState.active === 'print'}
      <PrintTab onPrint={generateAndPrint} busy={printBusy || !ready} />
    {:else if tabState.active === 'howto'}
      <HowToTab />
    {:else if tabState.active === 'steps'}
      <WalkthroughTab />
    {/if}
  </div>

  <BottomNav />
</div>

<div id="print-output" aria-hidden="true">
  {#each printGroups as group}
    <div class="page-group">
      {#each group.puzzles as puzzle}
        <PuzzleGrid {puzzle} />
      {/each}
      <div class="promo">{PROMO}</div>
    </div>
  {/each}
</div>
