<script lang="ts">
  import { onMount, mount } from 'svelte';
  import Header from './Header.svelte';
  import PlayTab from './tabs/PlayTab.svelte';
  import SolveTab from './tabs/SolveTab.svelte';
  import PrintTab from './tabs/PrintTab.svelte';
  import HowToTab from './tabs/HowToTab.svelte';
  import PuzzleGrid from './PuzzleGrid.svelte';
  import { initWasm, generatePuzzle } from '../wasm/api';
  import { loadRandomPuzzle, playState, setPuzzle } from '../state/puzzle.svelte';
  import { parsePuzzleFromUrl, syncUrl, tabFromUrl, tabState, setTab } from '../state/url.svelte';

  const PUZZLES_PER_PAGE = 6;
  const PROMO = `Doplo puzzles generated by ${window.location.origin}${window.location.pathname}`;

  let status = $state('Loading…');
  let ready = $state(false);
  let printBusy = $state(false);
  let printOutputEl: HTMLDivElement;

  // Shared "size to generate" between the Play and Print dropdowns.
  let selectedSize = $state(6);

  // Keep the URL in sync with state changes.
  $effect(() => {
    syncUrl(playState.puzzleData, tabState.active);
  });

  onMount(async () => {
    const fromUrl = parsePuzzleFromUrl();
    if (fromUrl) selectedSize = fromUrl.size;
    try {
      await initWasm();
      if (fromUrl) {
        setPuzzle(fromUrl, { preserveProgressIfSame: false });
      } else {
        loadRandomPuzzle(selectedSize);
      }
      const t = tabFromUrl();
      if (t !== 'play') setTab(t);
      // Pre-generate one page of 6×6 puzzles so a quick Ctrl+P from the browser
      // produces something printable without waiting on the Print tab.
      await fillPrintOutput(6, 1);
      ready = true;
      status = 'Ready';
    } catch (err) {
      status = 'Failed to load';
      console.error('Initialization failed:', err);
      throw err;
    }
  });

  // Render a generated puzzle into a detached container by mounting PuzzleGrid
  // — same component used by Play/Solve/HowTo, just used here for print pages.
  function renderPuzzleInto(parent: HTMLElement, size: number): void {
    const data = generatePuzzle(size);
    const wrap = document.createElement('div');
    parent.appendChild(wrap);
    const instance = mount(PuzzleGrid, { target: wrap, props: { puzzle: data } });
    // We don't need to keep a handle to unmount: print output is rebuilt on
    // each print run via `printOutputEl.replaceChildren()`.
    void instance;
  }

  async function fillPrintOutput(size: number, pages: number): Promise<void> {
    const total = pages * PUZZLES_PER_PAGE;
    printOutputEl.replaceChildren();
    let generated = 0;
    while (generated < total) {
      const pageSize = Math.min(PUZZLES_PER_PAGE, total - generated);
      const group = document.createElement('div');
      group.className = 'page-group';
      for (let i = 0; i < pageSize; i++) renderPuzzleInto(group, size);
      const promo = document.createElement('div');
      promo.className = 'promo';
      promo.textContent = PROMO;
      group.appendChild(promo);
      printOutputEl.appendChild(group);
      generated += pageSize;
      if (generated < total) await new Promise((resolve) => setTimeout(resolve, 0));
    }
  }

  async function generateAndPrint(size: number, pages: number): Promise<void> {
    printBusy = true;
    status = 'Generating…';
    try {
      await fillPrintOutput(size, pages);
      status = 'Ready';
      window.print();
    } finally {
      printBusy = false;
    }
  }
</script>

<Header {status} />

<main>
  <div style:display={tabState.active === 'play' ? 'block' : 'none'}>
    <PlayTab bind:selectedSize />
  </div>
  <div style:display={tabState.active === 'solve' ? 'block' : 'none'}>
    <SolveTab />
  </div>
  <div style:display={tabState.active === 'print' ? 'block' : 'none'}>
    <PrintTab bind:selectedSize onPrint={generateAndPrint} busy={printBusy || !ready} />
  </div>
  <div style:display={tabState.active === 'howto' ? 'block' : 'none'}>
    <HowToTab />
  </div>
</main>

<footer class="app-footer">
  Source code:
  <a href="https://github.com/Sjlver/rublock" target="_blank" rel="noopener noreferrer">
    github.com/Sjlver/rublock
  </a>
</footer>

<div id="print-output" aria-hidden="true" bind:this={printOutputEl}></div>
