<script lang="ts">
  import { onMount, mount } from 'svelte';
  import BottomNav from './BottomNav.svelte';
  import PlayTab from './tabs/PlayTab.svelte';
  import SolveTab from './tabs/SolveTab.svelte';
  import PrintTab from './tabs/PrintTab.svelte';
  import HowToTab from './tabs/HowToTab.svelte';
  import WalkthroughTab from './tabs/WalkthroughTab.svelte';
  import PuzzleGrid from './PuzzleGrid.svelte';
  import { initWasm, generatePuzzle } from '../wasm/api';
  import { loadRandomPuzzle, setPuzzle } from '../state/puzzle.svelte';
  import { parsePuzzleFromUrl, clearUrlParams, tabFromUrl, tabState, setTab } from '../state/url.svelte';
  import { trackEvent } from '../analytics';

  const PUZZLES_PER_PAGE = 6;
  const PROMO = `Doplo puzzles generated by ${window.location.origin}${window.location.pathname}`;

  let ready = $state(false);
  let printBusy = $state(false);
  let printOutputEl: HTMLDivElement;

  onMount(async () => {
    const fromUrl = parsePuzzleFromUrl();
    try {
      await initWasm();
      if (fromUrl) {
        setPuzzle(fromUrl, { preserveProgressIfSame: false });
      } else {
        loadRandomPuzzle(6);
      }
      // Per DESIGN_NOTES.md: clear the URL param after loading — keep URL clean.
      clearUrlParams();

      const t = tabFromUrl();
      if (t !== 'play') setTab(t);

      // Pre-generate one page so Ctrl+P works immediately.
      await fillPrintOutput(6, 1);
      ready = true;
    } catch (err) {
      console.error('Initialization failed:', err);
      throw err;
    }
  });

  function renderPuzzleInto(parent: HTMLElement, size: number): void {
    const data = generatePuzzle(size);
    const wrap = document.createElement('div');
    parent.appendChild(wrap);
    const instance = mount(PuzzleGrid, { target: wrap, props: { puzzle: data } });
    void instance;
  }

  async function fillPrintOutput(size: number, pages: number): Promise<void> {
    const total = pages * PUZZLES_PER_PAGE;
    printOutputEl.replaceChildren();
    let generated = 0;
    while (generated < total) {
      const pageSize = Math.min(PUZZLES_PER_PAGE, total - generated);
      const group = document.createElement('div');
      group.className = 'page-group';
      for (let i = 0; i < pageSize; i++) renderPuzzleInto(group, size);
      const promo = document.createElement('div');
      promo.className = 'promo';
      promo.textContent = PROMO;
      group.appendChild(promo);
      printOutputEl.appendChild(group);
      generated += pageSize;
      if (generated < total) await new Promise((resolve) => setTimeout(resolve, 0));
    }
  }

  async function generateAndPrint(size: number, pages: number): Promise<void> {
    printBusy = true;
    trackEvent(`rublock/print/print/${size}`);
    try {
      await fillPrintOutput(size, pages);
      window.print();
    } finally {
      printBusy = false;
    }
  }
</script>

<div class="app-shell">
  <div class="screen-content">
    {#if tabState.active === 'play'}
      <PlayTab />
    {:else if tabState.active === 'solve'}
      <SolveTab />
    {:else if tabState.active === 'print'}
      <PrintTab onPrint={generateAndPrint} busy={printBusy || !ready} />
    {:else if tabState.active === 'howto'}
      <HowToTab />
    {:else if tabState.active === 'steps'}
      <WalkthroughTab />
    {/if}
  </div>

  <BottomNav />
</div>

<div id="print-output" aria-hidden="true" bind:this={printOutputEl}></div>
